version: '3.9'

services:
  taskflow-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: 1.0.0
    image: baluthegoat/taskflow-app:latest
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    name: taskflow-mongo-data
