sonar.projectKey=CodeCraft-Titans_DSO101_SS26_Project
sonar.organization=codecraft-titans
sonar.projectName=DSO101_SS26_Project
sonar.projectVersion=1.0
sonar.sources=frontend,backend
sonar.tests=frontend,backend
sonar.test.inclusions=**/*.{test,spec}.{ts,tsx}
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8