# SonarCloud project settings
sonar.host.url=https://sonarcloud.io
sonar.projectKey=tadashi-dev-eng_dso-project
sonar.organization=tadashi-dev-eng
sonar.projectName=DSO101_SS26_Project
sonar.projectVersion=1.0

# Source and test files
sonar.sources=frontend,backend
sonar.tests=frontend,backend
sonar.test.inclusions=**/*.{test,spec}.{ts,tsx}

# Coverage report paths
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
