# SonarCloud project settings
sonar.host.url=https://sonarcloud.io
sonar.projectKey=tadashi-dev-eng_DSO101_SS26_Project
sonar.organization=tadashi-dev-eng
sonar.projectName=DSO101_SS26_Project
sonar.projectVersion=1.0

# Source and test files
sonar.sources=frontend,backend
sonar.tests=frontend,backend
sonar.test.inclusions=**/*.{test,spec}.{ts,tsx}

# Coverage report paths
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.coverage.exclusions=backend/generated/**,backend/dist/**,backend/prisma.config.ts,backend/src/index.ts,frontend/app/login/**,frontend/app/signup/**,frontend/app/tasks/**,frontend/app/layout.tsx,frontend/components/examples/**,frontend/components/ui/checkbox.tsx,frontend/components/ui/dialog.tsx,frontend/components/ui/input.tsx,frontend/components/ui/label.tsx,frontend/components/ui/separator.tsx
sonar.exclusions=backend/generated/**,backend/dist/**,backend/prisma.config.ts,backend/src/index.ts,frontend/components/examples/**,frontend/app/login/**,frontend/app/signup/**,frontend/app/tasks/**,frontend/app/layout.tsx,frontend/components/ui/checkbox.tsx,frontend/components/ui/dialog.tsx,frontend/components/ui/input.tsx,frontend/components/ui/label.tsx,frontend/components/ui/separator.tsx

# Encoding
sonar.sourceEncoding=UTF-8
